import type { INodeProperties } from 'n8n-workflow';

export const colleagueOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['colleague'] } },
		options: [
			{ name: 'Copy Preferences', value: 'copyPreferences', action: 'Copy preferences from another colleague' },
			{ name: 'Create', value: 'create', action: 'Create a colleague' },
			{ name: 'Delete', value: 'delete', action: 'Delete a colleague' },
			{ name: 'Get', value: 'get', action: 'Get a colleague' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many colleagues' },
			{ name: 'Get Many (Basic)', value: 'getManyBasic', action: 'Get many colleagues basic' },
			{ name: 'Get My Info', value: 'getMe', action: 'Get my info' },
			{ name: 'Get User Presence', value: 'getUserPresence', action: 'Get user presence by extension' },
			{ name: 'Set Batch Presence', value: 'setBatchPresence', action: 'Set batch presence for colleagues' },
			{ name: 'Update', value: 'update', action: 'Update a colleague' },
			{ name: 'Update User Presence', value: 'updateUserPresence', action: 'Update user presence by extension' },
		],
		default: 'getMany',
	},
];

export const colleagueFields: INodeProperties[] = [
	// ── Shared: colleague ID ───────────────────────────────────────────────────
	{
		displayName: 'Colleague ID',
		name: 'colleagueId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['colleague'], operation: ['get', 'delete', 'update', 'copyPreferences'] } },
		description: 'Numeric ID of the colleague',
	},

	// ── Get Many ───────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['colleague'], operation: ['getMany', 'getManyBasic'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: {
			show: { resource: ['colleague'], operation: ['getMany', 'getManyBasic'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['colleague'], operation: ['getMany', 'getManyBasic'] } },
		options: [
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter colleagues by name or extension',
			},
			{
				displayName: 'Sort Direction',
				name: 'dir',
				type: 'options',
				default: 'asc',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
			},
		],
	},

	// ── Create ─────────────────────────────────────────────────────────────────
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
	},
	{
		displayName: 'Extension',
		name: 'extension',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1001',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
		description: 'Internal extension number for the colleague',
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		required: true,
		default: 'user',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
		options: [
			{ name: 'Admin', value: 'admin' },
			{ name: 'Fax', value: 'fax' },
			{ name: 'Park Orbit', value: 'park_orbit' },
			{ name: 'Room', value: 'room' },
			{ name: 'User', value: 'user' },
		],
	},
	{
		displayName: 'License Type',
		name: 'licenseType',
		type: 'options',
		required: true,
		default: 'premium',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
		options: [
			{ name: 'Basic', value: 'basic' },
			{ name: 'Business', value: 'business' },
			{ name: 'Essential', value: 'essential' },
			{ name: 'Premium', value: 'premium' },
			{ name: 'Wizyconf', value: 'wizyconf' },
		],
	},
	{
		displayName: 'Dialplan',
		name: 'dialplan',
		type: 'string',
		required: true,
		default: 'users',
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
		description: 'Dialplan context for the colleague (typically "users")',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['colleague'], operation: ['create'] } },
		options: [
			{ displayName: 'Department', name: 'department', type: 'string', default: '' },
			{ displayName: 'Fax Dialplan', name: 'faxDialplan', type: 'string', default: '' },
			{ displayName: 'Fax Number', name: 'faxNumber', type: 'string', default: '' },
			{ displayName: 'Language', name: 'language', type: 'string', default: 'en', placeholder: 'en' },
			{ displayName: 'Login', name: 'login', type: 'string', default: '' },
			{ displayName: 'Mobile Phone', name: 'mobilePhone', type: 'string', default: '' },
			{ displayName: 'Office Phone', name: 'officePhone', type: 'string', default: '' },
			{ displayName: 'Password', name: 'password', type: 'string', typeOptions: { password: true }, default: '' },
			{ displayName: 'SIP Password', name: 'sipPassword', type: 'string', typeOptions: { password: true }, default: '' },
		],
	},

	// ── Update ─────────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['colleague'], operation: ['update'] } },
		options: [
			{ displayName: 'Department', name: 'department', type: 'string', default: '' },
			{ displayName: 'Dialplan', name: 'dialplan', type: 'string', default: '' },
			{ displayName: 'Email', name: 'email', type: 'string',
																																										placeholder: 'name@email.com', default: '' },
			{ displayName: 'Extension', name: 'extension', type: 'string', default: '' },
			{ displayName: 'Fax Dialplan', name: 'faxDialplan', type: 'string', default: '' },
			{ displayName: 'Fax Number', name: 'faxNumber', type: 'string', default: '' },
			{ displayName: 'Language', name: 'language', type: 'string', default: '' },
			{
				displayName: 'License Type',
				name: 'licenseType',
				type: 'options',
				default: 'premium',
				options: [
					{ name: 'Basic', value: 'basic' },
					{ name: 'Business', value: 'business' },
					{ name: 'Essential', value: 'essential' },
					{ name: 'Premium', value: 'premium' },
					{ name: 'Wizyconf', value: 'wizyconf' },
				],
			},
			{ displayName: 'Login', name: 'login', type: 'string', default: '' },
			{ displayName: 'Mobile Phone', name: 'mobilePhone', type: 'string', default: '' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{ displayName: 'Office Phone', name: 'officePhone', type: 'string', default: '' },
			{ displayName: 'Password', name: 'password', type: 'string', typeOptions: { password: true }, default: '' },
			{
				displayName: 'Role',
				name: 'role',
				type: 'options',
				default: 'user',
				options: [
					{ name: 'Admin', value: 'admin' },
					{ name: 'Fax', value: 'fax' },
					{ name: 'Park Orbit', value: 'park_orbit' },
					{ name: 'Room', value: 'room' },
					{ name: 'User', value: 'user' },
				],
			},
			{ displayName: 'SIP Password', name: 'sipPassword', type: 'string', typeOptions: { password: true }, default: '' },
		],
	},

	// ── Copy Preferences ───────────────────────────────────────────────────────
	{
		displayName: 'From Colleague ID',
		name: 'fromColleagueId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['colleague'], operation: ['copyPreferences'] } },
		description: 'Numeric ID of the colleague to copy preferences from',
	},

	// ── User Presence (by extension) ───────────────────────────────────────────
	{
		displayName: 'Extension',
		name: 'presenceExtension',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1001',
		displayOptions: { show: { resource: ['colleague'], operation: ['getUserPresence', 'updateUserPresence'] } },
		description: 'Extension of the user whose presence to get or update',
	},
	{
		displayName: 'Status',
		name: 'presenceStatus',
		type: 'options',
		required: true,
		default: 'available',
		displayOptions: { show: { resource: ['colleague'], operation: ['updateUserPresence'] } },
		options: [
			{ name: 'Available', value: 'available' },
			{ name: 'Away', value: 'away' },
			{ name: 'DND', value: 'dnd' },
			{ name: 'MUR', value: 'mur' },
		],
		description: 'Presence status to set',
	},
	{
		displayName: 'Additional Fields',
		name: 'userPresenceFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['colleague'], operation: ['updateUserPresence'] } },
		options: [
			{ displayName: 'Message', name: 'message', type: 'string', default: '', description: 'Presence message (e.g. "lunch")' },
			{ displayName: 'Until', name: 'until', type: 'string', default: '', placeholder: '19/09/2017 11:30', description: 'Expiry of the presence status, format "DD/MM/YYYY HH:mm" in UTC' },
		],
	},

	// ── Set Batch Presence ─────────────────────────────────────────────────────
	{
		displayName: 'Colleagues',
		name: 'colleagues',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		placeholder: 'Add Colleague',
		default: {},
		displayOptions: { show: { resource: ['colleague'], operation: ['setBatchPresence'] } },
		description: 'List of colleagues and their presence status to set',
		options: [
			{
				name: 'values',
				displayName: 'Colleague',
				values: [
					{
						displayName: 'Extension',
						name: 'extension',
						type: 'string',
						required: true,
						default: '',
						placeholder: '1001',
					},
					{
						displayName: 'Status',
						name: 'status',
						type: 'string',
						required: true,
						default: 'available',
						description: 'Presence status to set (e.g. available, busy, dnd, away)',
					},
				],
			},
		],
	},
];
