import type { INodeProperties } from 'n8n-workflow';

export const notificationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['notification'] } },
		options: [
			{
				name: 'Send',
				value: 'send',
				action: 'Send a notification',
				description: 'Send a notification or broadcast message to colleagues',
			},
		],
		default: 'send',
	},
];

export const notificationFields: INodeProperties[] = [
	{
		displayName: 'From',
		name: 'from',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Camera Lobby',
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		description: 'Source of the notification (e.g. device or system name)',
	},
	{
		displayName: 'Notification Type',
		name: 'notificationType',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'alarm',
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		description: 'Type of alert being generated (e.g. alarm, info)',
	},
	{
		displayName: 'Event',
		name: 'event',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Motion detected',
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		description: 'Description of what happened',
	},
	{
		displayName: 'Broadcast Message',
		name: 'broadcastMessage',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		description: 'Message to announce in the conference or broadcast',
	},
	{
		displayName: 'Broadcast ID',
		name: 'broadcastId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		description: 'ID of the broadcast group to send the message to',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['notification'], operation: ['send'] } },
		options: [
			{
				displayName: 'Confirmation Timeout (S)',
				name: 'confirmationTimeout',
				type: 'number',
				default: 30,
				description: 'Seconds to wait for confirmation after the notification starts',
			},
			{
				displayName: 'Custom Request ID',
				name: 'customRid',
				type: 'string',
				default: '',
				description: 'Custom request identifier for tracking',
			},
			{
				displayName: 'Origin',
				name: 'origin',
				type: 'string',
				default: '',
				description: 'Source system that generated the notification',
			},
			{
				displayName: 'Play Frequency (S)',
				name: 'playFrequency',
				type: 'number',
				default: 0,
				description: 'How often (in seconds) to repeat the broadcast message',
			},
			{
				displayName: 'Priority',
				name: 'priority',
				type: 'number',
				default: 0,
				description: 'Priority of the notification (higher = more urgent)',
			},
			{
				displayName: 'Queue Timeout (S)',
				name: 'queueTimeout',
				type: 'number',
				default: 60,
				description: 'Seconds a queued notification should wait before being processed',
			},
			{
				displayName: 'Skip Transcribe',
				name: 'skipTranscribe',
				type: 'boolean',
				default: false,
				description: 'Whether to skip transcribing the notification',
			},
		],
	},
];
